### ISSUE TITLE
Weird error when module name with page.

### ISSUE THREAD

**Issue by shankhadevpadam** [nWidart/laravel-modules#1072]
I generated the module name Page. In the create and edit, there is a weird error occur even I created all blade files in Modules/Page/Resources/views (index.blade.php, create.blade.php, edit.blade.php)

```
ErrorException
The "/home/ubuntu/html/laravel_projects/laravel_cms/resources/views/pages" directory does not exist. (View: /home/ubuntu/html/laravel_projects/laravel_cms/Modules/Page/Resources/views/create.blade.php) 
```

But this error is fixed when I have created pages directory inside the default resources/views/pages. But the index route is worked fine.

**Comment by nWidart** [comment]
Hi,

Strange, I haven't seen this before.
Which version of laravel are you using?

**Comment by shankhadevpadam** [comment]
Laravel 7.28.3

**Comment by lindo-llc** [comment]
What modifications have you done to the Page module? Have you been messing around with any of the providers? 
Because the error says: `The "/home/ubuntu/html/laravel_projects/laravel_cms/resources/views/pages" directory does not exist.` which makes me believe that something is up with the `registerViews()` method in the provider class

**Comment by shankhadevpadam** [comment]
This was fixed after laravel upgrade to version 8.
