### ISSUE TITLE
File does not exists modules.used

### ISSUE THREAD

**Issue by clonex1** [nWidart/laravel-modules#11]
Hi,

I was trying to execute the following command

`php artisan module:make-request LoginRequest`

But, I got the following error.

`File does not exist at path /laravel/storage/app/modules/modules.used`

**Comment by nWidart** [comment]
Hi,

That's because you didn't specify which module you want that request to be generated for.

When in doubt, you can always run `php artisan your-commnad --help` to known which arguments it needs.

You can always use the `php artisan module:use blog` command which would remember the module you're working on the so you don't have to specify the module name argument.

**Comment by clonex1** [comment]
It worked. Sorry for premature reporting.
Thanks!

**Comment by nWidart** [comment]
No worries, glad you got it working. 😄
