### ISSUE TITLE
Routes of modules are loaded after main app routes

### ISSUE THREAD

**Issue by lao9s** [nWidart/laravel-modules#1124]
If my **main app** in web.php i have this Route:
` Route::get('{any}', [PagesController::class, 'any'])->where('any', '.*')`

And a  **module**, in web.php have route:
` Route::get('/admin', [Admin::class, 'index'])->name('admin');`

Then the _**/admin**_ will fire PagesController action.

I think it happens because the routes for the module are loaded after the main application.

**Comment by nWidart** [comment]
Hi,

This package can't control this as routes are loaded via laravel.
I would suggest to not put this wildcard route in the application routes, but in your module with a high order.

**Comment by lao9s** [comment]
Hi,
Thank you for your response.

**Comment by virgiltu** [comment]
You can actually just create a module route called "website" and add that route there. The system looks for the modules names in alphabetical order. So any modules you add above will work fine because website is called last. Unless you have a module that starts with anything lower than W. 

![image](https://user-images.githubusercontent.com/7761519/116790399-c1392300-aa68-11eb-9323-ac3bc65f4d78.png)

**Comment by virgiltu** [comment]
> If my **main app** in web.php i have this Route:
> ` Route::get('{any}', [PagesController::class, 'any'])->where('any', '.*')`
> 
> And a **module**, in web.php have route:
> ` Route::get('/admin', [Admin::class, 'index'])->name('admin');`
> 
> Then the _**/admin**_ will fire PagesController action.
> 
> I think it happens because the routes for the module are loaded after the main application.

Also this type of route is also better because it will check if the route is edit or create 

''' Route::get('/{slug?}', [pagesController::class, 'index'] )->where(['slug' => '^(?!((.*/edit$)|(create$))).*\D+.*$']);'''

not sure if slug? or any is better but hey it works.
