### ISSUE TITLE
Load Vuejs components inside modules globally

### ISSUE THREAD

**Issue by Qoraiche** [nWidart/laravel-modules#1149]
I'm curious about any good approach to load all the modules Vuejs components, for example I've tried this:

In main application `bootstrap.js` file:

````
function requireAll(r) {
    r.keys().forEach((file) => {
        const name = file.replace('./','').replace('module.register.js','');
        require(name);
    });
}

requireAll(require.context('../../../Modules', true, /Resources\/module\.register.js$/));
````

every Module has a `module.register.js` file that will register all the Module vue components

but I got a webpack error `Critical dependency: the request of a dependency is an expression`

**Comment by n3m3s7s** [comment]
I can give you sime advices, hope they help:

- You have to be sure that the first paramater of require.context is a literal

- inside you forEach loop you have to call "r(name)" and not "require(name)", since the latter is generic require but You have to follow your context

- I suggest to update/upgrade to the latest webpack version with latest laravel-mix, they have resolved a lot of bugs
