### ISSUE TITLE
Interactive module creation

### ISSUE THREAD

**Issue by notiv-nt** [nWidart/laravel-modules#1192]
The idea is taken from vue/cli's app creation 

<details>
<summary>Video</summary>

https://user-images.githubusercontent.com/10743009/108764330-83e58000-7563-11eb-8c67-5ef3f90aa40f.mov
</details>

I suggest to do the same.
For that we need to have checkboxes, and i've found [nunomaduro/laravel-console-menu](https://github.com/nunomaduro/laravel-console-menu) a wrapper around [php-school/cli-menu](https://github.com/php-school/cli-menu). Not ideal but it works.

<details>
<summary>Usage example</summary>

https://user-images.githubusercontent.com/10743009/108765437-d2dfe500-7564-11eb-908e-47593ca32128.mov
</details>

[Demo repository](https://github.com/notiv-nt/laravel-make-module-example), [command](https://github.com/notiv-nt/laravel-make-module-example/blob/master/app/Console/Commands/MakeModule.php#L37)

The question is do we need it ?

**Comment by maxcelos** [comment]
I've created myself a command to generate models with all Repository Pattern files needed to my projects. It wraps out the laravel-modules commands and generators, so I can still use this package as base and get the updates but creating modules with my preferences. I even use my own stubs.

So, since the maintainers has no much to deal with issues here, I suggest you do the same I do and implement it by your own and maybe ship this as a package for others.
