### ISSUE TITLE
Model is added to the wrong module

### ISSUE THREAD

**Issue by rabol** [nWidart/laravel-modules#1199]
If you forget to specify the Module, the model is created in the first available Module

```
php artisan module:make-model -m Test
```

e.g.
if you have 2 Modules, it will then create the model in the first

It should give an error a argument is missing

**Comment by maxcelos** [comment]
There is a command in this package to make possible not repeat the module name every time. Checkout the `module:use ModuleName`.

So it's not a missing argument since it is optional.

By default the module "in use" is the first one. Then now you may want suggest that the module in use should be the last created, but it would solve the problem for you, but make a lot of people that get used to the `module:use` command unhappy.
