### ISSUE TITLE
laravel 9 test

### ISSUE THREAD

**Issue by hooman-mirghasemi** [nWidart/laravel-modules#1371]
--coverage option added to laravel 9 runinng test, but it dont report any thing from codes inside modules!
it run tests inside modules becuse I addes this to phpunite.xml:
 <testsuite name="ModulesUnit">
            <directory suffix="Test.php">./Modules/**/Tests/Unit</directory>
        </testsuite>
        <testsuite name="ModulesFeature">
            <directory suffix="Test.php">./Modules/**/Tests/Feature</directory>
        </testsuite>

but do not report covarage

**Comment by hooman-mirghasemi** [comment]
in phpunite.xml i add:
    <coverage processUncoveredFiles="true">
        <include>
           <directory suffix=".php">./app</directory>-
            <directory suffix=".php">./Modules/*/Http</directory>
            <directory suffix=".php">./Modules/*/Models/</directory>
        </include>
    </coverage>


but it dont show coverge of code in module folders

**Comment by ronfuller** [comment]
@hooman-mirghasemi  I struggled with this for a while and researched all the posts referring to code coverage and modules.
I could only get code coverage to work in src or app folders. You can test this by simply adding a src folder and putting an example file then adding /src to phpunit.xml

I ended up moving my modules to a src folder by doing the following

edit config/modules.php
 ```
'paths' => [ 
   'modules' => base_path('src')
   ...
   ]
```
  edit composer.json
  
  under "autoload"
```
     "psr-4": {
            "App\\": "app/",
            "Modules\\": "src/",
            ...
       }

```       
       
   My phpunit.xml is as follows
   
   ```
<testsuites>
       <testsuite name="Unit">
            <directory suffix="Test.php">./tests/Unit</directory>
        </testsuite>
        <testsuite name="Feature">
            <directory suffix="Test.php">./tests/Feature</directory>
        </testsuite>
         <testsuite name="Modules">
            <directory suffix="Test.php">./src/**/Tests/Feature</directory>
            <directory suffix="Test.php">./src/**/Tests/Unit</directory>
        </testsuite>
    </testsuites>
   <coverage processUncoveredFiles="true">
        <include>
            <directory suffix=".php">./src</directory>
        </include>
         <exclude>
            <directory suffix=".php">./src/**/Routes</directory>
            <directory suffix=".php">./src/**/Resources</directory>
            <directory suffix=".php">./src/**/Tests</directory>
            <directory suffix=".php">./src/**/Config</directory>
            <directory suffix=".php">./src/**/Infrastructure</directory>
        </exclude>
    </coverage>
```

**Comment by bradsi** [comment]
@hooman-mirghasemi @ronfuller 
Appreciate this is an old issue but I ran into this yesterday and found this issue when searching, so just adding this for future reference in case anyone else comes across this.

I'm using pcov for code coverage and my issue was that the pcov directory was set to `/app`. This will be the default for Laravel projects unless it's explicitly configured.

So, code coverage should be run with the following command (as an example):
```
php -d pcov.directory="/Users/bradsi/code/my-project" ./vendor/bin/pest --coverage
```

This will set the coverage directory to the root of the project, instead of `/app`, and will cover your `/modules` folder.

However, in my case this pcov.directory setting was not applied. I have had this working before, so maybe there is something else in my local environment that was preventing it from running. If this happens to you, try setting the pcov.directory variable explicitly in the `php.ini` file.

**Comment by backstageel** [comment]
Thanks @ronfuller, that worked for me.

Just wondering why only those folders works for coverage...
