### ISSUE TITLE
Content in views is not up to date in the browser.

### ISSUE THREAD

**Issue by dieterdd** [nWidart/laravel-modules#165]
Content in views is not up to date in the browser. Cookie and cache has been deleted. Also the Artisan commands view: clear and cache: clear was made. Why the changes in the view are not displayed in. In the beginning, everything has gone. Have also tried with different browsers. Can someone give me a tip. Many Thanks.
best regards
Dieter

**Comment by dieterdd** [comment]
My problem was the command   php artisan vendor:publish   it has me all the folders and files copied to another place and I have not noticed.
best regards
Dieter

**Comment by nWidart** [comment]
Indeed if you published the views that's used. 👍

**Comment by irvine48** [comment]
Hi @nWidart ,

Spending 5 hours only realize this is the issue my view not updating, tried to remove storage cache, clear browser cache, reinstall vagrant box, reboot computer, even delete the blade file from my module. Still it can load the non updated view. Finally get the idea i did a vendor publish this morning.

Here is my question here is why need to publish all views into project views folder, since we are toward to modules direction?

**Comment by nWidart** [comment]
You don't need to. You can remove the publish view feature from your service provider if you don't need that functionality.

Where this functionality can become useful is a module that you will publish / re-use on other projects, so that you can customise the views of said module, without having to edit the module itself.
