### ISSUE TITLE
Modules not loading on hosting service

### ISSUE THREAD

**Issue by AlisherN** [nWidart/laravel-modules#1716]
I'm using this package on my project designed in Laravel 10. It's working on a localhost without any problem. But, when I uploaded it on a hosting service, the package not loading.

It's giving 404 error, when I visit a page from a package generated module route (however, this route is working properly on the localhost).

In a `composer.json` file:

```json
{
"psr-4": {
            "App\\": "app/",
            "Modules\\": "modules/",
            "Database\\Factories\\": "database/factories/",
            "Database\\Seeders\\": "database/seeders/"
        }
}
```

**Comment by dcblogdev** [comment]
Have you maybe got routes cached?

Try to clear them I tend to do 

'php artisan optimize:clear'

Then run 'php artisan optimize' again to recache everything.

**Comment by AlisherN** [comment]
> Have you maybe got routes cached?
> 
> Try to clear them I tend to do
> 
> 'php artisan optimize:clear'
> 
> Then run 'php artisan optimize' again to recache everything.

No, it's not because of the route cache. I've cleared cache several times.

**Comment by AlisherN** [comment]
I had to set all service providers of modules into providers list in config/app.php. After that, it worked.

**Comment by dcblogdev** [comment]
glad you solved it.

**Comment by AlisherNPortfolio** [comment]
Finally, I found the solution!
I changed `base_path('Modules')` into `base_config('modules')` in `modules.php` config file's `path.modules`. Because, my modules folder name starts with lowercase as `modules`. And in linux hosting service, `glob` function in `Illuminate\Filesystem\Filesystem`'s glob function looking for folders and files in `Modules` folder.
