### ISSUE TITLE
Lumen Compatibility

### ISSUE THREAD

**Issue by pedrosoares** [nWidart/laravel-modules#310]
I clone your project to fix the incompatibility with Lumen. How i send to this repo the changes? I dont find a "contribute guide".
The changes that i made to make the compatibility:

- Created LumenRepository
- Created LumenModule
- Upgraded LumenModuleServiceProvider 
- Created lumen-stubs
-- Fix start.stub
-- Fix routes.stub
-- Fix scafold/provider.stub
-- Fix controller.stub

**Comment by nWidart** [comment]
Check out this page: https://help.github.com/articles/creating-a-pull-request/

**Comment by nWidart** [comment]
@deividaspetraitis How did you handle the issue of laravel-modules having laravel/framework as a dependency?

**Comment by deividaspetraitis** [comment]
@nWidart I didn't. I think there is no way to do that since this package supports both: Laravel and Lumen. That means package must to download files for both frameworks and separated providers guarantees ( LaravelModuleServiceProvider, LumenModuleServiceProvider ) that required dependencies will be loaded for certain framework. 
@pedrosoares could you please provide more details what kind of incompatibility you're facing, because I'm using it with lumen with no probs at all.
