### ISSUE TITLE
Api version handling

### ISSUE THREAD

**Issue by sk2304** [nWidart/laravel-modules#455]
Hello
How can i follow the below structure :-
moduels/api/v1
moduels/api/v2

I tried but not worked

Thanks

**Comment by rockymontana** [comment]
It’s being loaded from start.php that is being loaded from the service provider iirc.

**Comment by sk2304** [comment]
Thanks for your response @rockymontana 
Can you please tell me what configuration is required to work properly
http://localhost/api/v1/users
http://localhost/api/v2/users
Thanks
Sandeep

**Comment by rockymontana** [comment]
Not really sure why you want to add the complexity of modules if you don’t have a basic understanding regarding Laravel’s routing mechanism. 

I would recommend going through the laracasts series on Laravel basics, and then use the framework as it is until you’ve gotten a good idea on how to work with these modules.
Otherwise you’ll keep running into problems and eventually you’ll just get tired of it.

No offense.
