### ISSUE TITLE
Laravel modules disable xdebug

### ISSUE THREAD

**Issue by jschubi** [nWidart/laravel-modules#608]
Hi, 
i use laravel modules and it works really fine.
But one big problem is, that i can't use xdebug anymore since i installed laravel modules.
I tried to remove your package and then it works to use xdebug. So why it wont work with your package ? Is there a workaround to use it and xdebug ?

**Comment by nWidart** [comment]
Hi,

You should still be able to use xdebug. I use it still with laravel modules without issues.

The issue arises when trying to dump something related to the modules. Like all available modules etc.
This is because, currently, the laravel application is sent to the modules. Which is too much for xdebug to handle out of the box. Probably increasing a setting can help.

**Comment by jschubi** [comment]
Hi, 
thanks for your response. 
May it possible, that you provide me your `ext-xdebug.ini` and phpstorm xdebug config.
I think it would help me.

**Comment by nWidart** [comment]
Sorry, I'm on a new mac and haven't set that up yet.
I don't remember changing anything on the old mac though. You should be able to find documentation on the xdebug site though.


I'll close this for now as it's configuration related issue 😄
