### ISSUE TITLE
Create a Kernel.php file in module

### ISSUE THREAD

**Issue by kamov** [nWidart/laravel-modules#674]
Can I create a Kernel.php class in a module?

**Comment by nWidart** [comment]
Yes, you can create any file / class inside your modules.

**Comment by kamov** [comment]
Thanks for quick reply.
As I understand I can add Kernel.php in my Modules/MODULE/Http/ folder and then change in bootstrap/app.php the loading of the Kernel.php ?

I am not sure if I can have multiple kernel class? But seem yes.

How the module know that exist a kernel file and then load it?

**Comment by nWidart** [comment]
Autoloading is handled by composer. 
In your main composer.json file you have an autoload section where you added something for this package. That's how it's autoloaded.

It will work because in the bootstrap/app.php file you call the kernel class using its fully qualified name, using the `::class` syntax.

**Comment by kamov** [comment]
I will try thanks.
