### ISSUE TITLE
Change views with "hook" using modules?

### ISSUE THREAD

**Issue by RishabSwift** [nWidart/laravel-modules#69]
Hello, please consider this:

The default website has a `about` view which display's a view. If I create a module that displays an alert in the `about` view, how can I place the alert in the top of the about view?

In other words, how can I hook my code in other controllers, view, etc?

**Comment by nWidart** [comment]
Hi, this is not related to the package, please refer to the laravel documentation.

This is done as any laravel app by calling that view where you want.

**Comment by RishabSwift** [comment]
It is related to this package because laravel docs doesn't have anything to do with "hooks". If one is using this package to modify the `about` view, how would they do it?

How does one use this package to do such task? Because I haven't found a way of doing this whatsoever.

>This is done as any laravel app by calling that view where you want.

What does this mean? I know how views work. I don't have any idea how I would be modifying a view using modules, instead of creating a new view in the module and calling that instead of the original view.

Please help me out on this. The docs are not helpful when it comes to doing this in laravel-modules. However, it is an excellent package that I see myself using.

Thank you.

**Comment by mikemand** [comment]
@RishabSwift Views can be registered for the module using the following method: https://laravel.com/docs/5.3/packages#views

So in your Module's service provider, make sure you call the method `loadViewsFrom` in the `boot` method like so: `$this->loadViewsFrom(__DIR__ . '/../Resources/views', 'module');` where `__DIR__ . '/../Resources/views'` is the path to your module's views and `module` is the name of your module, in lowercase (snake_case if multiple words).

To override, all you have to do is put the view in `/resources/views/module/` and Laravel automatically uses it instead of the one provided with the package (in this case, module).
