### ISSUE TITLE
CRUD Generator

### ISSUE THREAD

**Issue by BreakerYouko** [nWidart/laravel-modules#82]
What do you think about implement a single command to create MVC instead of doing it manually?

**Comment by sebastiaanluca** [comment]
Just FYI, I forked this package over at https://github.com/sebastiaanluca/laravel-modules in order to create a command and some sub commands that create the entire flow for a resource. I.e. `php artisan module:make:migration users` and `php artisan module:make:resource user` to create a database structure and have the second command generate a module with a service provider, router, controller, store and update validators, repository, entity, model, interfaces, etc based on that table. This would save me several hours per resource (and days per project) as everything would be pre-filled and it'd only be a matter of deleting what's irrelevant.

Note that it's still in development phase and I'm changing things regularly. I'm also extending it to make use of rinvex/repository, sebastiaanluca/laravel-routers, and others.

**Comment by nWidart** [comment]
Why not contributing here ?

**Comment by sebastiaanluca** [comment]
Needed something quick and dirty a while ago. Just checked out your latest master branch so I can start with a clean slate. Looking into applying my code to that base in an orderly fashion so I can submit PRs while still having a usable combination of all those tweaks and extensions that I can use in a new project.

One of the issues is that I need functionality I want to have available in this package, but you probably don't want in there. I've added `rinvex/repository` which I've forked and refactored too with entities and whatnot, validators, resource commands, reading tables and generated stubs based on that, laravel-router, … Was thinking of trying to port the stubs to Blade templates, because the more conditional they get, the harder it is to generate a template by just replacing text between $$ tags.

How do you accept pull requests? The smaller, the better?

**Comment by imagina** [comment]
Hum, I converted the Crud  in Backpack (https://packagist.org/packages/backpack/crud) to use it in Asgard. The code is not very clean but it worked fast with the same Asgard Admin, etc. So it was very easy for me to create some simple additional modules for an admin i needed urgently. 

I would love to see that functionality in the Asgard core. 

My Asgard Module right now is in https://github.com/imagina/CRUD  and it's working very well for some small modules i needed. I connected the permissions to be compatible with Asgard. What do you think about something like this @nWidart ? I'm planning to clean the code to keep using it in the future.

Regards

**Comment by nWidart** [comment]
I'll close this due to inactivity.

**Comment by teddywest32** [comment]
Is there any mechanism to generate CRUD similar to this [package](https://github.com/InfyOmLabs/laravel-generator) for modules development??
