### ISSUE TITLE
Can't make group modules

### ISSUE THREAD

**Issue by rizalmx** [nWidart/laravel-modules#84]
is possible to make a group of modules? 
when i write this command

`php artisan module:make Backend\user`

`[Nwidart\Modules\Exceptions\ModuleNotFoundException]
  Module [Backend\user] does not exist!
`

and than the routes file
`

Route::group(['middleware' => 'web', 'prefix' => 'backend\user', 'namespace' => 'Modules\Backend\user\Http\Controllers'], function()
{
    Route::get('/', 'Backend\userController@index');
});
`

**Comment by armababy** [comment]
There is no such thing as group modules. If you need common space for different functionality you use entities for that.

**Comment by webds** [comment]
--->>If you need common space for different functionality you use entities for that.
Write an example please.

Here is my example.
group delivery :
modules/delivery/fedex/Http....
modules/delivery/ups/Http....
modules/delivery/dhl/Http....

---
group payments:
modules/payments/paypal/Http....
modules/payments/scrill/Http....
modules/payments/stripe/Http....
--
It's more convenient when we see a catalog with all payment system modules, all delivery service modules, etc.
Also, each module itself can be updated, disabled, enabled.


Therefore, I also have a question - how to properly organize this in this package.

**Comment by dcblogdev** [comment]
you cannot create nested modules but you can create multiple folders for modules to be loaded from so you could have a payments folder that contains 3 modules PayPal, scroll and Stripe.

In the `modules.php` config file change:

```php
'scan' => [
        'enabled' => false,
        'paths' => [
            base_path('vendor/*/*'),
        ],
    ],
 ```
 
 to
 
 ```php
'scan' => [
        'enabled' => true,
        'paths' => [
            base_path('Payments')
        ],
 ],
 ```
 
 Then create a root folder `Payments`
 
 The autoload the folder in `composer.json`
 
```
 "psr-4": {
            "App\\": "app/",
            "Modules\\": "Modules/",
            "Payments\\": "Payments/"
        },
   ```
   
   Now you can have modules inside the Payments folder, you could need to change the namespace on those modules to use `Payments` instead of `Modules`

**Comment by webds** [comment]
This is not quite what you need and, in my opinion, is not correct regarding structure and convenience.

1. The correct architecture is one directory with modules, which should be in the root.
2. As I wrote above, modules can be not only payment modules, but also modules of delivery services and other types.
3. The correct and understandable structure is when:
3.1. There is a directory of modules in the root.
3.2 there is a group payments / delivery / other....
3.3 modules that are already included in these groups.
Here's how to set it up so that it can work like that?
-- root
---- modules
------delivery
--------fedex
--------ups
--------dhl
------payments
--------paypal
--------scrill
--------stripe
------other
--------nameModule-1
--------nameModule-2
--------nameModule-1

**Comment by iwasherefirst2** [comment]
> This is not quite what you need and, in my opinion, is not correct regarding structure and convenience.
> 
>     1. The correct architecture is one directory with modules, which should be in the root.
> 
>     2. As I wrote above, modules can be not only payment modules, but also modules of delivery services and other types.
> 
>     3. The correct and understandable structure is when:
>        3.1. There is a directory of modules in the root.
>        3.2 there is a group payments / delivery / other....
>        3.3 modules that are already included in these groups.
>        Here's how to set it up so that it can work like that?
>        -- root
>        ---- modules
>        ------delivery
>        --------fedex
>        --------ups
>        --------dhl
>        ------payments
>        --------paypal
>        --------scrill
>        --------stripe
>        ------other
>        --------nameModule-1
>        --------nameModule-2
>        --------nameModule-1

I completely agree. I transitioned from a huge legacy app to a modular architecture, and having all modules at the same level quickly becomes a mess. Grouping them by type makes a lot of sense.

This feature has been requested multiple times:

    https://github.com/nWidart/laravel-modules/issues/952
    https://github.com/nWidart/laravel-modules/issues/842
    https://github.com/nWidart/laravel-modules/issues/829

But it seems like the decision was made not to support it.
