### ISSUE TITLE
Laravel Routes + VueJS, routes are being overwritten

### ISSUE THREAD

**Issue by Keilost** [nWidart/laravel-modules#845]
Hello,

Well, I have a problem with my routes, all requests related to the Modules folders doesn't work.

In my project-folder/routes/web.php I must use in that way because my front is in VueJs:

`Route::get('/{any}', 'ApplicationController')->where('any', '.*');`

Ok, I was using routes into the main api.php file, working fine, but when I put in Modules/ModuleName/Routes/api.php the route doesn't work:

`Route::group(['middleware' => 'auth:api'], function () {

    Route::get(
        'opportunity/kanban',
        '\App\Modules\Opportunity\Http\Controllers\OpportunityController@kanbanList'
    );

    Route::get(
        'opportunity/channel-sale',
        '\App\Modules\Opportunity\Http\Controllers\OpportunityController@channelSaleList'
    );

    Route::get(
        'opportunity/flow-steps',
        '\App\Modules\Opportunity\Http\Controllers\OpportunityController@flowStepList'
    );
});`

If I remove the route::get('any')... from main web.php it works, 
I believe the routes are having some kind of conflict.

**Comment by mikemand** [comment]
The main Laravel routes are registered before the ones from your module(s). The way to fix this is to put your module's route service provider ABOVE Laravel's route service provider in your `config/app.php` file.

I do not know how auto-discovery will affect this - if you're using that in your modules.

Another fix may be to put this package's service provider (instead of having to do each module's route service provider) above the Laravel route service provider, but I am not sure what other unintended consequences that would bring.

**Comment by Keilost** [comment]
Hmm, ok, I will try this on the monday, thanks!

**Comment by Keilost** [comment]
https://stackoverflow.com/questions/58243133/laravel-modules-vuejs-routes-are-being-overwritten/58244647#58244647

**Comment by mikemand** [comment]
Thank you @Keilost. I forgot about `Route::fallback`.
