### ISSUE TITLE
Generator doesn't follow config file

### ISSUE THREAD

**Issue by abdulrahman19** [nWidart/laravel-modules#866]
Laravel: 6.2
Lararvel-module: 6.1

I try to remove some folder I don't need from module generator, and flagged their `generate` key on config file to `false` but nothing effected

after some trace, I found the problem with method `generateFiles` on `ModuleGenerator` line `360`

you need to use `continue`  keyword not `$this->filesystem->makeDirectory($dir, 0775, true);`

![carbon](https://user-images.githubusercontent.com/22733622/68083941-b1bb2880-fe37-11e9-9283-ae8877c7eb5b.png)

please fix it ASAP

**Comment by nWidart** [comment]
Hi,

Thanks for reporting.

> please fix it ASAP

This is opensource, feel free to submit a tested PR.

**Comment by nWidart** [comment]
I was able to reproduce the issue, however, the fix is not as simple as you suggest.

Doing this is correct, but will require a breaking change of adding more keys in the `generator` configuration key, like for example:

```
'routes' => ['path' => 'Routes', 'generate' => true],
'views-layouts' => ['path' => 'Resources/views/layouts', 'generate' => true],
```

Which are implicit based on the files configured. Every file configured should have a generator folder configuration too, basically.

Then, the seeders are not generated in that location but in `generateResources` method. So there should be a condition for each resource generated (seeds, providers, etc.).

I'm not sure there's a good way of solved this without a breaking change.

**Comment by abdulrahman19** [comment]
I noticed this too when I was trying to fix the issue for the PR. I'll check it deeply at home and tell you what I think.

**Comment by nWidart** [comment]
I've fixed the resource related generation here: https://github.com/nWidart/laravel-modules/commit/2e487606ed98f402f9e146711c941df54ea5fb69

**Comment by nWidart** [comment]
I think the other ones will have to wait until the next major release.

**Comment by juanpscotto** [comment]
Any news? I'm waiting.

**Comment by nWidart** [comment]
I'm waiting for your PR too.
