### ISSUE TITLE
Unable to create module in Laravel 6.2

### ISSUE THREAD

**Issue by Yeakleang** [nWidart/laravel-modules#873]
After I installed this package and follow the configuration's instruction, and run command `php artisan module:make Test`, I got the errors below:
```
Nwidart\Modules\Exceptions\InvalidActivatorClass  : You don't have a valid activator configuration class. This might be due to your config being out of date. 
 Run php artisan vendor:publish --provider="Nwidart\Modules\LaravelModulesServiceProvider" --force to publish the up to date configuration

  at E:\e-commerce\vendor\nwidart\laravel-modules\src\Exceptions\InvalidActivatorClass.php:9
     5| class InvalidActivatorClass extends \Exception
     6| {
     7|     public static function missingConfig()
     8|     {
  >  9|         return new static("You don't have a valid activator configuration class. This might be due to your config being out of date. \n Run php artisan vendor:publish --provider=\"Nwidart\Modules\LaravelModulesServiceProvider\" --force to publish the up to date configuration");
    10|     }
    11| }
    12| 

  Exception trace:

  1   Nwidart\Modules\Exceptions\InvalidActivatorClass::missingConfig()
      E:\e-commerce\vendor\nwidart\laravel-modules\src\LaravelModulesServiceProvider.php:61

  2   Nwidart\Modules\LaravelModulesServiceProvider::Nwidart\Modules\{closure}(Object(Illuminate\Foundation\Application), [])
      E:\e-commerce\vendor\laravel\framework\src\Illuminate\Container\Container.php:800

  Please use the argument -v to see more details.
```
I don't know what the hell is going on here.

**Comment by Yeakleang** [comment]
Now it is resolved by clear the configuration cache.

**Comment by mark-emery** [comment]
I am getting the same error from trying to clear clear the config cache. How do I manually clear the cache?

php artisan config:clear

   Nwidart\Modules\Exceptions\InvalidActivatorClass  : You don't have a valid activator configuration class. This might be due to your config being out of date.
 Run php artisan vendor:publish --provider="Nwidart\Modules\LaravelModulesServiceProvider" --force to publish the up to date configuration

  at C:\inetpub\NAES\vendor\nwidart\laravel-modules\src\Exceptions\InvalidActivatorClass.php:9
     5| class InvalidActivatorClass extends \Exception
     6| {
     7|     public static function missingConfig()
     8|     {
  >  9|         return new static("You don't have a valid activator configuration class. This might be due to your config being out of date. \n Run php artisan vendor:publish --provider=\"Nwidart\Modules\LaravelModulesServiceProvider\" --force to publish the up to date configuration");
    10|     }
    11| }
    12|

  Exception trace:

  1   Nwidart\Modules\Exceptions\InvalidActivatorClass::missingConfig()
      C:\inetpub\NAES\vendor\nwidart\laravel-modules\src\LaravelModulesServiceProvider.php:61

  2   Nwidart\Modules\LaravelModulesServiceProvider::Nwidart\Modules\{closure}(Object(Illuminate\Foundation\Application), [])
      C:\inetpub\NAES\vendor\laravel\framework\src\Illuminate\Container\Container.php:799

  Please use the argument -v to see more details.
