### ISSUE TITLE
URL Generation webpack return public path instead of url

### ISSUE THREAD

**Issue by dreamond** [nWidart/laravel-modules#887]
Hello,
I run into an error as the links generated by this command

```php
@foreach($jsFiles as $jsFile)
        <script src="{!! Module::asset($moduleName.':js/'.$jsFile) !!}"></script>
    @endforeach
```

return full public path inside the url instead of relative path

https://myapp.com/home/myapp/public/modules/mytestmodule/js/myscript.js

Without compilation, it shows instead

//myapp.com/modules/mytestmodule/js/myscript.js

I found out that those link instead ot have https://...../myscript.js doesn't display web protocol.

Any idea how to solve this issue?

**Comment by mikemand** [comment]
It's because of this line here: https://github.com/nWidart/laravel-modules/blob/4151f9f42887524783385dce0f5bf8735b6b73a3/src/FileRepository.php#L534

You can add the `https:` right after `src="` and before the `{` if you need them, otherwise it should be protocol agnostic. This is a holdover from before SSL became so accessible. [Here's an old article](https://www.paulirish.com/2010/the-protocol-relative-url/) about it (and he even has an update from over 5 years ago about it becoming an anti-pattern now 😲).

I would assume that a PR would be accepted to correct this behavior. (Right, @nWidart?)

**Comment by dreamond** [comment]
Thx a lot
