### ISSUE TITLE
[QUESTION] Why don't use l5-repository instead of Base*Name*Repository in app/Repositories?

### ISSUE THREAD

**Issue by pysoftware** [nWidart/laravel-modules#923]

**Comment by nWidart** [comment]
What's l5 repository?

**Comment by pysoftware** [comment]
https://github.com/andersao/l5-repository
i thought before it was in setup of ur project

**Comment by nWidart** [comment]
Ah, no we don't plan to use that by default. You're free to use it though.

**Comment by mrlinnth** [comment]
Didn't mean to open the closed issue.
I just wanna share my solution since I am also using laravel-modules and l5-repository packages together.

Created a custom artisan command file which will generate files under correct module folder. Check the gist for the code.

[https://gist.github.com/mrlinnth/4508eb22afab288fca61634ee6d6a2c3](https://gist.github.com/mrlinnth/4508eb22afab288fca61634ee6d6a2c3)

**Comment by garbinmarcelo** [comment]
> Didn't mean to open the closed issue.
> I just wanna share my solution since I am also using laravel-modules and l5-repository packages together.
> 
> Created a custom artisan command file which will generate files under correct module folder. Check the gist for the code.
> 
> https://gist.github.com/mrlinnth/4508eb22afab288fca61634ee6d6a2c3

Are you still using repositories with this module? It's working fine?

Sorry to answer something older, but I want to learn more about and maybe use repositories.

**Comment by mrlinnth** [comment]
@garbinmarcelo sorry for late reply. I have used it up to Laravel 7, I think. It was fine.

Haven't used with Laravel 8 yet.
