### ISSUE TITLE
Can I create in the modules part some folder that includes some modules?

### ISSUE THREAD

**Issue by GGWPTIERTERIO** [nWidart/laravel-modules#934]
For example, in the module part, you can create a package that represents a management and in that package create the modules that represent the sub-management.

Modules:
 -Management 
        - sub-management
             -config
             -console
             -database
             -......
        - sub-management        
             -config
             -console
             -database
             -......
 -Management 
        - sub-management
             -config
             -console
             -database
             -......
        - sub-management        
             -config
             -console
             -database
             -......

**Comment by okangr** [comment]
Hi I am new to this package but if I am not mistaken you can't do that. However, even if you could, it wouldn't be wise to do it since a management could have hundreds of sub managements, in which case you could end up with hundreds of modules. And maintaining those module will be a nightmare. 

I would recommend you to rethink your design and maybe use only 1 management module and declare a self referential relationship using eloquent models. (A management model "hasMany" sub management modules and again a management module "belongsTo" another management module).

**Comment by nWidart** [comment]
I agree with @okangr , I wouldn't advise doing this in the first place. And indeed it's not possible to do it currently.

**Comment by GGWPTIERTERIO** [comment]
Thank you for your support. I will close the case.
