### ISSUE TITLE
Clarify the connection between modules

### ISSUE THREAD

**Issue by KingErfan** [nWidart/laravel-modules#961]
Hey there 
Thank you for this great package...
I have a question about the connection between different modules.
Let's assume that we have a laravel application that contains 4 modules: Home, FAQ, Blog, Comment
for every blog or every question in faq you can have comments to reply that specific question or blog 
then how can I define the comment module that would work with both faq and blog.
The comment table on the database should define as a polymorphic one 
but how would the model of comment and the use of comment in blog and faq be?
thanks for your help ....

**Comment by nWidart** [comment]
Hi,

You can call classes from other modules, that's totally possible. So you can have eloquent relationships across modules too.
I would advise against this, but it's just php/laravel

**Comment by KingErfan** [comment]
Yeah, it is possible to do that but then, the modules will be dependent on each other. won't they?

**Comment by nWidart** [comment]
Indeed the modules would depend on each other, that's why I'd advise against it. Now, of course, some relations are "ok", in my eyes, like the User module, which will most likely be referenced from other modules.
It's all up to you to decide on how much you're ok to have this coupling.

One way to avoiding coupling between modules can be handled via events. Module 1 triggers an event, and other modules can listen to this event and choose to act on it.

**Comment by KingErfan** [comment]
Thanks for your help. I didn't think about events...

**Comment by xcesaralejandro** [comment]
Hello @MohammadErfan-Jabbari , how did you solve this? I understand that event logic is a good alternative but it often triggers the n+1 problem and is not as efficient for queries with a lot of data.

On the other hand, I also share the idea mentioned above about the bad practice of excessively relating the modules, since they would generate unnecessary coupling (except for users).

I'm thinking about not atomizing my modules so much so that the models coexist inside without problems. I don't really like that idea either since I would end up building very large modules and the beginning would be lost a bit.

Sometimes I will need to load models something like: relationship1.relation2.relation3.relation4 ; If they are different modules, structuring that data becomes too complex.

The tipping question might be: If I need to do eagger loading between models, then should they all be in the same module?

Modularization is a good alternative, but knowing more about your experience could be very valuable for me and other users who come here later.

Could you tell us what you have done, what has worked well and what mistakes you would not make again?
